### PR TITLE
Add superobbing capability for AHI observations

### PR DESCRIPTION
**Pull request by ibanos90**
This PR adds the superobbing capability for AHI observations. Giving the half width of the superobbing grid as an entry parameter, the code computes the average brightness temperature in the box defined using that parameter. This code is adapted from https://github.com/wrf-model/WRF/blob/develop/var/da/da_radiance/da_read_obs_netcdf4ahi_jaxa.inc and follows the same implementation as for ABI observations from GOES-16. The debugging build flags for the goes_abi code are removed. The following figures show the brightness temperature results for AHI observations after using this converter for 2018-04-15T00 channel 8 (a) without superobbing and  (b) with superobbing on a grid of 59x59 pixels:
**a)**
RAW_2018041500_b8coverage_test_20220721_ch8_08_12
**b)**
RAW_2018041500_b8coverage_test_20220721_superobbing59X59

**Issue closed**
Closes https://github.com/NCAR/obs2ioda/issues/1

### CODE REVIEW

**Comment by ibanos90** [comment]
@liujake

**Review by jjguerrette — COMMENTED** [review]
@ibanos90, I did not look through the details, but the output from your presentation looks reasonable.  Approval pending.  Do you mind uploading two images to the PR description, one with superobbing, and one without?

**Review by liujake — APPROVED** [review]
Approve given the results. Not check code details.

**Comment by ibanos90** [comment]
> @ibanos90, I did not look through the details, but the output from your presentation looks reasonable. Approval pending. Do you mind uploading two images to the PR description, one with superobbing, and one without?

Thanks for the suggestion @jjguerrette. I added the figures to the PR description.

**Review by jjguerrette — APPROVED** [review]

**Pull request merged**
