### PR TITLE
Adding obserror for CrIS

### PR DESCRIPTION
**Pull request by zhumingying**
Revised define_mod.f90 with adding obs errors for CrIS-FSR.

For data after 2021: Observation errors for the CrIS-FSR with 431 channels have been added.
For data before 2021: If you are processing CrIS data with 399 channels, you will need to manually add the observation errors.

The obs error assigned here are from the two obs file in UFO (It's easy to copy and paste):
ufo-data/testinput_tier_1/cris-fsr_n20_obs_2020121500_m.nc4
ufo-data/testinput_tier_1/cris-fsr_npp_obs_2018041500_m.nc4

The cris-fsr_npp 's errors in this PR are the same as the following file
https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/gfs.v16.3.16/fix/fix_gsi/global_satinfo.txt
while cris-fsr_n20 's errors are different from global_satinfo.txt.

### CODE REVIEW

**Comment by zhumingying** [comment]
Revised define_mod.f90 with adding obs errors for CrIS

**Review by liujake — APPROVED** [review]

**Comment by ibanos90** [comment]
Hi @zhumingying, can you add some brief description to the PR? Thanks!

**Comment by junmeiban** [comment]
Here are more information:
The obs error assigned here are from the two obs file in UFO (It's easy to copy and paste):
`ufo-data/testinput_tier_1/cris-fsr_n20_obs_2020121500_m.nc4`
`ufo-data/testinput_tier_1/cris-fsr_npp_obs_2018041500_m.nc4`

The `cris-fsr_npp` 's errors in this PR are the same as the following file 
https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/gfs.v16.3.16/fix/fix_gsi/global_satinfo.txt 
while `cris-fsr_n20` 's errors are different from global_satinfo.txt .

**Comment by ibanos90** [comment]
> Here are more information: The obs error assigned here are from the two obs file in UFO (It's easy to copy and paste): `ufo-data/testinput_tier_1/cris-fsr_n20_obs_2020121500_m.nc4` `ufo-data/testinput_tier_1/cris-fsr_npp_obs_2018041500_m.nc4`
> 
> The `cris-fsr_npp` 's errors in this PR are the same as the following file https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/gfs.v16.3.16/fix/fix_gsi/global_satinfo.txt while `cris-fsr_n20` 's errors are different from global_satinfo.txt .

Thanks @junmeiban!

**Comment by liujake** [comment]
I edited the PR message section using Zhuming and Junmei's text.

@zhumingying Please learn from other repos' PRs how to make a 'GOOD' PR with necessary PR message provided.

**Comment by junmeiban** [comment]
I think it’s okay that the errors of `cris-fsr_n20` are currently different from those in `global_satinfo.txt`.  I'm unsure how they update the observation errors for `cris-fsr_n20` in `ufo-data/testinput_tier_1/cris-fsr_n20_obs_2020121500_m.nc4`. If degradation continues from the Cris assimilation, we could consider trying the same error as in `global_satinfo.txt` for `cris-fsr_n20`.

**Review by junmeiban — APPROVED** [review]

**Comment by liujake** [comment]
What @zhumingying needs to check first is the channel selection from https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/gfs.v16.3.16/fix/fix_gsi/global_satinfo.txt (i.e., -1 is unuse), to see if our current use of cris channels is consistent with operational use (not for high-peaking channels as we have a low model top).

**Comment by zhumingying** [comment]
I  add two lines:
For data after 2021: Observation errors for the CrIS-FSR with 431 channels
have been added.
For data before 2021: If you are processing CrIS data with 399 channels,
you will need to manually add the observation errors.

**Review by ibanos90 — APPROVED** [review]

**Pull request merged**
